const db=require('../config/db');
exports.getAll=async(req,res,next)=>{try{const{period_id,phase}=req.query;let q=`SELECT i.*,p.label AS period_label,COUNT(ia.id) AS aspect_count FROM instruments i LEFT JOIN periods p ON p.id=i.period_id LEFT JOIN instrument_aspects ia ON ia.instrument_id=i.id WHERE 1=1`;const params=[];if(period_id){q+=' AND i.period_id=?';params.push(period_id);}if(phase){q+=' AND i.phase=?';params.push(phase);}q+=' GROUP BY i.id ORDER BY i.phase,i.created_at DESC';const[rows]=await db.query(q,params);res.json(rows);}catch(e){next(e);}};
exports.getOne=async(req,res,next)=>{try{const[[ins]]=await db.query(`SELECT i.*,p.label AS period_label FROM instruments i LEFT JOIN periods p ON p.id=i.period_id WHERE i.id=?`,[req.params.id]);if(!ins)return res.status(404).json({message:'Instrumen tidak ditemukan'});const[aspects]=await db.query('SELECT * FROM instrument_aspects WHERE instrument_id=? ORDER BY order_no',[req.params.id]);res.json({...ins,aspects});}catch(e){next(e);}};
exports.create=async(req,res,next)=>{try{const{period_id,phase,title,description,max_score}=req.body;if(!period_id||!phase||!title)return res.status(400).json({message:'period_id, phase, title wajib'});const[r]=await db.query('INSERT INTO instruments (period_id,phase,title,description,max_score,created_by) VALUES (?,?,?,?,?,?)',[period_id,phase,title,description,max_score||90,req.user.id]);res.status(201).json({message:'Instrumen dibuat',id:r.insertId});}catch(e){next(e);}};
exports.update=async(req,res,next)=>{try{const{title,description,max_score}=req.body;await db.query('UPDATE instruments SET title=?,description=?,max_score=? WHERE id=?',[title,description,max_score,req.params.id]);res.json({message:'Instrumen diperbarui'});}catch(e){next(e);}};
exports.remove=async(req,res,next)=>{try{await db.query('DELETE FROM instruments WHERE id=?',[req.params.id]);res.json({message:'Instrumen dihapus'});}catch(e){next(e);}};
exports.addAspect=async(req,res,next)=>{try{const{aspect_name,score_3,score_2,score_1,order_no}=req.body;if(!aspect_name)return res.status(400).json({message:'aspect_name wajib'});const[r]=await db.query('INSERT INTO instrument_aspects (instrument_id,order_no,aspect_name,score_3,score_2,score_1) VALUES (?,?,?,?,?,?)',[req.params.id,order_no||1,aspect_name,score_3||'Baik',score_2||'Cukup',score_1||'Kurang']);res.status(201).json({message:'Aspek ditambahkan',id:r.insertId});}catch(e){next(e);}};
exports.updateAspect=async(req,res,next)=>{try{const{aspect_name,score_3,score_2,score_1,order_no}=req.body;await db.query('UPDATE instrument_aspects SET order_no=?,aspect_name=?,score_3=?,score_2=?,score_1=? WHERE id=?',[order_no||1,aspect_name,score_3,score_2,score_1,req.params.aid]);res.json({message:'Aspek diperbarui'});}catch(e){next(e);}};
exports.removeAspect=async(req,res,next)=>{try{await db.query('DELETE FROM instrument_aspects WHERE id=?',[req.params.aid]);res.json({message:'Aspek dihapus'});}catch(e){next(e);}};
